### ISSUE TITLE
Wrong bower main at most recent tag

### ISSUE THREAD

**Issue by jehna** [saimon24/ng-twitter#5]
Using bower to fetch the latest version (1.3.0) will have a wrong `main` on the `bower.json` file. This can be fixed by adding a new tag (1.4.0) to the project HEAD

**Comment by saimon24** [comment]
Fixed!

**Comment by jehna** [comment]
Remembered to push the tag? Don't see it yet at the github

**Comment by saimon24** [comment]
Sorry about that, now it's fixed right?

**Comment by jehna** [comment]
Yep, it's good!
