### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on..

### ISSUE THREAD

**Issue by rafasegat** [saimon24/ng-twitter#7]
Occurring this error

XMLHttpRequest cannot load https://api.twitter.com/1.1/statuses/home_timeline.json?count=5. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 400.

**Comment by saimon24** [comment]
HTTP status code 400 means you are not logged in. Are other requests working? Please check if you really got a valid token and can grab data from other endpoints.

**Comment by alvarosabu** [comment]
I have a question Saimon24, If I'm not using cordova instead only angularjs, how can I get the oauthToken, there is some module or something, if you have some example like that I will thank you a lot to see it, thank you

**Comment by rafasegat** [comment]
saimon24, its working perfectly. My token access secret was incorrect. 

Thanks so much

**Comment by saimon24** [comment]
@Shevastation plz open this again as a different issue!

**Comment by Madebyspeedster** [comment]
hey to everyone!!!  i'm just need to make first request to get access token so i'm create  post request 
 this.http.post('https://api.twitter.com/oauth2/token', JSON.stringify(data)).subscribe();
in my data i have  next: 
 // 'OAuth oauth_consumer_key': 'my consumer key',
    // 'oauth_nonce' : 'kYjzVBB8Y0ZFabxSWbWovY3uYSQ2pTgmZeNu2VS4cg',
    // 'oauth_signature': 'tnnArxj06cWHq44gCs1OSKk%2FjLY%3D',
    // 'oauth_signature_method': 'HMAC-SHA1',
    // 'oauth_timestamp': '1318622958',
    // 'oauth_token': '370773112-GmHxMAgYyLbNEtIKZeRNFsMKPR9EyMZeS9weJAEb',
    // 'oauth_version': '1.0'


after request i have statsus code 403   :
Failed to load https://api.twitter.com/oauth2/token: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://app.cinema.com:3000' is therefore not allowed access. The response had HTTP status code 403.


and  in response i have :
{"errors":[{"code":99,"message":"Unable to verify your credentials","label":"authenticity_token_error"}]}



what i do wrong please ??
